// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRAUG5BGVgxgGA49s1GNtbSza-P7j2_JQ',
    appId: '1:745502044965:web:94eac8eb4c8148ea6ea0cc',
    messagingSenderId: '745502044965',
    projectId: 'social-media-app-334ab',
    authDomain: 'social-media-app-334ab.firebaseapp.com',
    storageBucket: 'social-media-app-334ab.appspot.com',
    measurementId: 'G-VNYWZRK80Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdQzCPKFWMRKox1M3ypNDF8EVJMDlKrw',
    appId: '1:745502044965:android:56fdefd5df52944d6ea0cc',
    messagingSenderId: '745502044965',
    projectId: 'social-media-app-334ab',
    storageBucket: 'social-media-app-334ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhGT2hb9jf0mufKG5J_KgLNcwUQX5sIw',
    appId: '1:745502044965:ios:4d55d99f7f70c7466ea0cc',
    messagingSenderId: '745502044965',
    projectId: 'social-media-app-334ab',
    storageBucket: 'social-media-app-334ab.appspot.com',
    androidClientId: '745502044965-eqmetjtko12dejebdflp7pnjeglmvbql.apps.googleusercontent.com',
    iosClientId: '745502044965-3v8i50bgspljtggopadmvu6k47in40bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRhGT2hb9jf0mufKG5J_KgLNcwUQX5sIw',
    appId: '1:745502044965:ios:4d55d99f7f70c7466ea0cc',
    messagingSenderId: '745502044965',
    projectId: 'social-media-app-334ab',
    storageBucket: 'social-media-app-334ab.appspot.com',
    androidClientId: '745502044965-eqmetjtko12dejebdflp7pnjeglmvbql.apps.googleusercontent.com',
    iosClientId: '745502044965-3v8i50bgspljtggopadmvu6k47in40bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
